# Site settings
description: > # this means to ignore newlines until "baseurl:"
  Your Music Connection.
baseurl: "AirboundEnt" # the subpath of your site, e.g. /blog/
url: "http://AirboundEnt.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
